_G.EXBossData.RegisterBossPreset("raid_dps", {
    key = "PresetConfig",
    name = "预设配置",
    author = "预设配置",
    builtIn = true,
    events = {
        [16] = { enabled = false },
        [24] = { enabled = false },
        [25] = { enabled = false },
        [35] = { enabled = false },
        [59] = { enabled = false },
        [60] = { enabled = false },
        [64] = { enabled = false },
        [78] = { enabled = false },
        [82] = { enabled = false },
        [94] = { enabled = false },
        [111] = { enabled = false },
        [134] = { enabled = false },
        [137] = { enabled = false },
        [150] = { enabled = false },
        [156] = { enabled = false },
        [164] = { enabled = false },
        [206] = { enabled = false },
        [210] = { enabled = false },
        [220] = { enabled = false },
        [221] = { enabled = false },
        [226] = { enabled = false },
        [239] = { enabled = false },
        [251] = { enabled = false },
        [276] = { enabled = false },
        [278] = { enabled = false },
        [282] = { enabled = false },
        [286] = { enabled = false },
        [294] = { enabled = false },
        [302] = { enabled = false },
        [306] = { enabled = false },
        [364] = { enabled = false },
        [420] = { enabled = false },
        [492] = { enabled = false },
        [556] = { enabled = false },
    },
})
