local _, Addon = ...

local root = "Interface\\AddOns\\" .. Addon.Identity.addonName .. "\\Assets\\"
local function asset(fileName)
    return root .. fileName
end

Addon.Assets = {
    windowBackground = asset("surface_window_v2.tga"),
    panelBackground = asset("surface_panel_v2.tga"),
    insetBackground = asset("surface_inset_v2.tga"),
    heroPlate = asset("surface_hero_v2.tga"),
    classHeroPlates = {
        DEATHKNIGHT = asset("surface_hero_deathknight.tga"),
        DEMONHUNTER = asset("surface_hero_demonhunter.tga"),
        DRUID = asset("surface_hero_druid.tga"),
        EVOKER = asset("surface_hero_evoker.tga"),
        HUNTER = asset("surface_hero_hunter.tga"),
        MAGE = asset("surface_hero_mage.tga"),
        MONK = asset("surface_hero_monk.tga"),
        PALADIN = asset("surface_hero_paladin.tga"),
        PRIEST = asset("surface_hero_priest.tga"),
        ROGUE = asset("surface_hero_rogue.tga"),
        SHAMAN = asset("surface_hero_shaman.tga"),
        WARLOCK = asset("surface_hero_warlock.tga"),
        WARRIOR = asset("surface_hero_warrior.tga"),
    },
    cardPlate = asset("surface_card_v2.tga"),
    vaultCard = asset("surface_vault_card.tga"),
    cardInset = asset("surface_card_inset_v2.tga"),
    sidebarPlate = asset("surface_sidebar_v2.tga"),
    utilityPlate = asset("surface_utility_v2.tga"),
    contentPlate = asset("surface_content_v2.tga"),
    menuPlate = asset("surface_menu_v2.tga"),
    titleMedallion = asset("vaultloom_title_medallion.tga"),
    titleBarStone = asset("title_bar_stone.tga"),
    titleCloseButton = asset("title_close_button.tga"),
    roundedColorBorder = asset("rounded_color_border.tga"),
    roundedIconMask = asset("rounded_icon_mask.tga"),
    roundedStatusLineMask = asset("rounded_status_line_mask.tga"),
    buttonNormal = asset("button_reskin_normal.tga"),
    buttonHover = asset("button_reskin_hover.tga"),
    buttonPressed = asset("button_reskin_pressed.tga"),
    buttonSlices = {
        normal = {
            left = asset("button_warm_frame_normal_left.tga"),
            middle = asset("button_warm_frame_normal_middle.tga"),
            middleLong = asset("button_warm_frame_normal_middle_long.tga"),
            right = asset("button_warm_frame_normal_right.tga"),
        },
        hover = {
            left = asset("button_warm_frame_hover_left.tga"),
            middle = asset("button_warm_frame_hover_middle.tga"),
            middleLong = asset("button_warm_frame_hover_middle_long.tga"),
            right = asset("button_warm_frame_hover_right.tga"),
        },
        pressed = {
            left = asset("button_warm_frame_pressed_left.tga"),
            middle = asset("button_warm_frame_pressed_middle.tga"),
            middleLong = asset("button_warm_frame_pressed_middle_long.tga"),
            right = asset("button_warm_frame_pressed_right.tga"),
        },
        active = {
            left = asset("button_warm_frame_active_left.tga"),
            middle = asset("button_warm_frame_active_middle.tga"),
            middleLong = asset("button_warm_frame_active_middle_long.tga"),
            right = asset("button_warm_frame_active_right.tga"),
        },
        disabled = {
            left = asset("button_warm_frame_disabled_left.tga"),
            middle = asset("button_warm_frame_disabled_middle.tga"),
            middleLong = asset("button_warm_frame_disabled_middle_long.tga"),
            right = asset("button_warm_frame_disabled_right.tga"),
        },
    },
    tabNormal = asset("tab_reskin_normal.tga"),
    tabHover = asset("tab_reskin_hover.tga"),
    tabActive = asset("tab_reskin_active.tga"),
    row = asset("surface_row_v2.tga"),
    scrollTrack = asset("scroll_track_reskin.tga"),
    scrollThumb = asset("scroll_thumb_reskin.tga"),
    scrollArrowUp = asset("arrow_up_small.tga"),
    scrollArrowDown = asset("arrow_down_small.tga"),
    classBackplate = asset("class_backplate_reskin.tga"),
    classRing = asset("class_ring_reskin.tga"),
    barBackground = asset("bar_bg_reskin.tga"),
    barFill = asset("bar_fill_reskin.tga"),
    barOverlay = asset("bar_overlay_reskin.tga"),
    barMarker = asset("bar_marker_reskin.tga"),
    barSpark = asset("bar_spark_reskin.tga"),
    statusBadgeComplete = asset("status_badge_complete.tga"),
    statusBadgeFailed = asset("status_badge_failed.tga"),
    statusBadgeLocked = asset("status_badge_locked.tga"),
    statusBadgeMissing = asset("status_badge_missing.tga"),
    statusBadgeTurnIn = asset("status_badge_turnin.tga"),
    statusBadgeOpen = asset("status_badge_open.tga"),
    statusBadgeRepeatable = asset("status_badge_repeatable.tga"),
    statusBadgeWarning = asset("status_badge_warning.tga"),
    statusBadgePending = asset("status_badge_pending.tga"),
    statusBadgeSaltherilFavor = asset("status_badge_saltheril_favor.tga"),
    statusBadgeFrame = asset("status_badge_frame.tga"),
    vaultRewardIcon = asset("vault_reward_chest.tga"),
    vaultRewardRing = asset("gathering_pin_ring_world.tga"),
    vaultSimpleCategories = {
        raid = {
            atlas = "evergreen-weeklyrewards-category-raids",
        },
        dungeon = {
            atlas = "evergreen-weeklyrewards-category-dungeons",
        },
        world = {
            atlas = "evergreen-weeklyrewards-category-world",
        },
    },
    specializationBackgrounds = {
        [250] = "talents-background-deathknight-blood",
        [251] = "talents-background-deathknight-frost",
        [252] = "talents-background-deathknight-unholy",
        [577] = "talents-background-demonhunter-havoc",
        [581] = "talents-background-demonhunter-vengeance",
        [1480] = "talents-background-demonhunter-devourer",
        [102] = "talents-background-druid-balance",
        [103] = "talents-background-druid-feral",
        [104] = "talents-background-druid-guardian",
        [105] = "talents-background-druid-restoration",
        [1467] = "talents-background-evoker-devastation",
        [1468] = "talents-background-evoker-preservation",
        [1473] = "talents-background-evoker-augmentation",
        [253] = "talents-background-hunter-beastmastery",
        [254] = "talents-background-hunter-marksmanship",
        [255] = "talents-background-hunter-survival",
        [62] = "talents-background-mage-arcane",
        [63] = "talents-background-mage-fire",
        [64] = "talents-background-mage-frost",
        [268] = "talents-background-monk-brewmaster",
        [269] = "talents-background-monk-windwalker",
        [270] = "talents-background-monk-mistweaver",
        [65] = "talents-background-paladin-holy",
        [66] = "talents-background-paladin-protection",
        [70] = "talents-background-paladin-retribution",
        [256] = "talents-background-priest-discipline",
        [257] = "talents-background-priest-holy",
        [258] = "talents-background-priest-shadow",
        [259] = "talents-background-rogue-assassination",
        [260] = "talents-background-rogue-outlaw",
        [261] = "talents-background-rogue-subtlety",
        [262] = "talents-background-shaman-elemental",
        [263] = "talents-background-shaman-enhancement",
        [264] = "talents-background-shaman-restoration",
        [265] = "talents-background-warlock-affliction",
        [266] = "talents-background-warlock-demonology",
        [267] = "talents-background-warlock-destruction",
        [71] = "talents-background-warrior-arms",
        [72] = "talents-background-warrior-fury",
        [73] = "talents-background-warrior-protection",
    },
    professionBadges = {
        alchemy = asset("status_badge_profession_alchemy.tga"),
        blacksmithing = asset("status_badge_profession_blacksmithing.tga"),
        enchanting = asset("status_badge_profession_enchanting.tga"),
        engineering = asset("status_badge_profession_engineering.tga"),
        herbalism = asset("status_badge_profession_herbalism.tga"),
        inscription = asset("status_badge_profession_inscription.tga"),
        jewelcrafting = asset("status_badge_profession_jewelcrafting.tga"),
        leatherworking = asset("status_badge_profession_leatherworking.tga"),
        mining = asset("status_badge_profession_mining.tga"),
        skinning = asset("status_badge_profession_skinning.tga"),
        tailoring = asset("status_badge_profession_tailoring.tga"),
    },
    raidTrackerNone = asset("raid_tracker_none_reskin.tga"),
    raidTrackerWish = asset("raid_tracker_wish_reskin.tga"),
    raidTrackerObtained = asset("raid_tracker_obtained_reskin.tga"),
    compendiumIconBorder = asset("compendium_icon_border.tga"),
    compendiumWaypointIcon = asset("compendium_waypoint_icon.tga"),
    preyHuntIcons = asset("prey_hunt_icons.tga"),
    classIcons = {
        DEATHKNIGHT = asset("class_icon_deathknight.tga"),
        DEMONHUNTER = asset("class_icon_demonhunter.tga"),
        DRUID = asset("class_icon_druid.tga"),
        EVOKER = asset("class_icon_evoker.tga"),
        HUNTER = asset("class_icon_hunter.tga"),
        MAGE = asset("class_icon_mage.tga"),
        MONK = asset("class_icon_monk.tga"),
        PALADIN = asset("class_icon_paladin.tga"),
        PRIEST = asset("class_icon_priest.tga"),
        ROGUE = asset("class_icon_rogue.tga"),
        SHAMAN = asset("class_icon_shaman.tga"),
        WARLOCK = asset("class_icon_warlock.tga"),
        WARRIOR = asset("class_icon_warrior.tga"),
    },
}
