---@diagnostic disable: undefined-global
-- Auto-generated from EXBOSS private aura pipeline. Do not edit manually.
_G.EXBOSS_PRIVATE_AURA_DATA = {
    raid = {
        [1701] = {
            encounterID = 1701,
            dungeon = "通天峰",
            boss = "高阶贤者维里克斯 (High Sage Viryx)",
            spells = {
                [1253541] = {
                    spellID = 1253541,
                    name = "灼烧射线",
                    voiceCategory = 3,
                    sourceNPCIDs = { 76266 },
                    sources = { "High Sage Viryx" },
                },
                [1253543] = {
                    spellID = 1253543,
                    name = "灼烧射线",
                    voiceCategory = 3,
                    sourceNPCIDs = { 76285 },
                    sources = { "Arakkoa Magnifying Glass" },
                },
            },
        },
        [2562] = {
            encounterID = 2562,
            dungeon = "艾杰斯亚学院",
            boss = "维克萨姆斯 (Vexamus)",
            spells = {
                [386201] = {
                    spellID = 386201,
                    name = "腐化法力",
                    voiceCategory = 3,
                    sourceNPCIDs = { 194181 },
                    sources = { "Vexamus" },
                },
                [391977] = {
                    spellID = 391977,
                    name = "涌动超载",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    sources = { "Environment" },
                },
            },
        },
        [2563] = {
            encounterID = 2563,
            dungeon = "艾杰斯亚学院",
            boss = "茂林古树 (Overgrown Ancient)",
            spells = {
                [388544] = {
                    spellID = 388544,
                    name = "裂树击",
                    voiceCategory = 3,
                    sourceNPCIDs = { 196482 },
                    sources = { "Overgrown Ancient" },
                },
            },
        },
        [2564] = {
            encounterID = 2564,
            dungeon = "艾杰斯亚学院",
            boss = "克罗兹 (Crawth)",
            spells = {
                [376449] = {
                    spellID = 376449,
                    name = "火焰风暴",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    sources = { "Goal of the Searing Blaze" },
                },
                [376760] = {
                    spellID = 376760,
                    name = "狂风之力",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    sources = { "Goal of the Rushing Winds" },
                },
                [377009] = {
                    spellID = 377009,
                    name = "震耳尖啸",
                    voiceCategory = 3,
                    sourceNPCIDs = { 191736 },
                    sources = { "Crawth" },
                },
            },
        },
        [2565] = {
            encounterID = 2565,
            dungeon = "艾杰斯亚学院",
            boss = "多拉苟萨的回响 (Echo of Doragosa)",
            spells = {
                [389007] = {
                    spellID = 389007,
                    name = "野蛮能量",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    sources = { "Environment" },
                },
                [389011] = {
                    spellID = 389011,
                    name = "势不可挡",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    sources = { "Environment" },
                },
            },
        },
        [3057] = {
            encounterID = 3057,
            dungeon = "风行者之塔",
            boss = "被遗弃的二人组 (Derelict Duo)",
            spells = {
                [472793] = {
                    spellID = 472793,
                    name = "猛力拖拽",
                    voiceCategory = 3,
                    sourceNPCIDs = { 231629 },
                    sources = { "Latch" },
                },
                [474129] = {
                    spellID = 474129,
                    name = "飞溅喷吐",
                    voiceCategory = 3,
                    sourceNPCIDs = { 231629 },
                    sources = { "Latch" },
                },
            },
        },
        [3058] = {
            encounterID = 3058,
            dungeon = "风行者之塔",
            boss = "指挥官克罗鲁科 (Commander Kroluk)",
            spells = {
                [467620] = {
                    spellID = 467620,
                    name = "暴怒",
                    voiceCategory = 3,
                    sourceNPCIDs = { 231631 },
                    sources = { "Commander Kroluk" },
                },
                [470966] = {
                    spellID = 470966,
                    name = "剑刃风暴",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    sources = { "Environment" },
                },
                [1283247] = {
                    spellID = 1283247,
                    name = "无情跳跃",
                    voiceCategory = 3,
                    sourceNPCIDs = { 231631 },
                    sources = { "Commander Kroluk" },
                },
            },
        },
        [3072] = {
            encounterID = 3072,
            dungeon = "魔导师平台",
            boss = "瑟拉奈尔·日鞭 (Selanar Sunlash)",
            spells = {
                [1225792] = {
                    spellID = 1225792,
                    name = "符文印记",
                    voiceCategory = 3,
                    sourceNPCIDs = { 231863 },
                    sources = { "Seranel Sunlash" },
                },
            },
        },
        [3073] = {
            encounterID = 3073,
            dungeon = "魔导师平台",
            boss = "吉美尔鲁斯 (Gemellus)",
            spells = {
                [1253709] = {
                    spellID = 1253709,
                    name = "神经链接",
                    voiceCategory = 3,
                    sourceNPCIDs = { 231864, 239636 },
                    sources = { "Gemellus" },
                },
            },
        },
        [3074] = {
            encounterID = 3074,
            dungeon = "魔导师平台",
            boss = "迪詹崔乌斯 (Degentrius)",
            spells = {
                [1269631] = {
                    spellID = 1269631,
                    name = "熵能宝珠",
                    voiceCategory = 3,
                    sourceNPCIDs = { 231865 },
                    sources = { "Degentrius" },
                },
            },
        },
        [3159] = {
            encounterID = 3159,
            dungeon = "孢陨幽境",
            boss = "腐沼 (Rotmire)",
            spells = {
                [1221639] = {
                    spellID = 1221639,
                    name = "蕈菇人幼体",
                    voiceCategory = 3,
                    sourceNPCIDs = { 238696 },
                    sources = { "Shroomling" },
                },
                [1221714] = {
                    spellID = 1221714,
                    name = "毒药爆发",
                    voiceCategory = 3,
                    sourceNPCIDs = { 238699 },
                    sources = { "Sporecap" },
                },
                [1222088] = {
                    spellID = 1222088,
                    name = "溃烂藤蔓",
                    voiceCategory = 3,
                    sourceNPCIDs = { 238693 },
                    sources = { "Rotmire" },
                },
                [1222129] = {
                    spellID = 1222129,
                    name = "凋零之藤",
                    voiceCategory = 3,
                    sourceNPCIDs = { 238693 },
                    sources = { "Rotmire" },
                },
                [1299508] = {
                    spellID = 1299508,
                    name = "真菌人幼体",
                    voiceCategory = 3,
                    sourceNPCIDs = { 239020 },
                    sources = { "Fungling" },
                },
            },
        },
        [3176] = {
            encounterID = 3176,
            dungeon = "虚影尖塔",
            boss = "元首阿福扎恩 (Imperator Averzian)",
            spells = {
                [1249265] = {
                    spellID = 1249265,
                    name = "幽影坍缩",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240435 },
                    sources = { "Imperator Averzian" },
                },
                [1255680] = {
                    spellID = 1255680,
                    name = "啃噬虚空",
                    voiceCategory = 3,
                    sourceNPCIDs = { 251176 },
                    sources = { "Voidmaw" },
                },
                [1260203] = {
                    spellID = 1260203,
                    name = "幽影坍缩",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240435 },
                    sources = { "Imperator Averzian" },
                },
                [1260981] = {
                    spellID = 1260981,
                    name = "无尽行军",
                    voiceCategory = 3,
                    sourceNPCIDs = { 254079 },
                    sources = { "Obscurion Endwalker" },
                },
                [1265540] = {
                    spellID = 1265540,
                    name = "黑化创伤",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240435 },
                    sources = { "Imperator Averzian" },
                },
                [1275059] = {
                    spellID = 1275059,
                    name = "黑色瘴气",
                    voiceCategory = 3,
                    sourceNPCIDs = { 257950 },
                    sources = { "Abyssal Malus" },
                },
                [1280023] = {
                    spellID = 1280023,
                    name = "虚空标记",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240435 },
                    sources = { "Imperator Averzian" },
                },
                [1280075] = {
                    spellID = 1280075,
                    name = "徘徊黑暗",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240435 },
                    sources = { "Imperator Averzian" },
                },
                [1284786] = {
                    spellID = 1284786,
                    name = "暗影方阵",
                    voiceCategory = 3,
                    sourceNPCIDs = { 259928, 260659 },
                    sources = { "Obscurion Endwalker" },
                },
            },
        },
        [3177] = {
            encounterID = 3177,
            dungeon = "虚影尖塔",
            boss = "弗拉希乌斯 (Vorasius)",
            spells = {
                [1241844] = {
                    spellID = 1241844,
                    name = "碾碎",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240434 },
                    sources = { "Vorasius" },
                },
                [1243270] = {
                    spellID = 1243270,
                    name = "黑暗黏液",
                    voiceCategory = 3,
                    sourceNPCIDs = { 253475, 255418 },
                    sources = { "Blistercreep" },
                },
                [1254113] = {
                    spellID = 1254113,
                    name = "锁定",
                    voiceCategory = 3,
                    sourceNPCIDs = { 253475, 255418 },
                    sources = { "Blistercreep" },
                },
                [1259186] = {
                    spellID = 1259186,
                    name = "气泡爆裂",
                    voiceCategory = 3,
                    sourceNPCIDs = { 253475 },
                    sources = { "Blistercreep" },
                },
                [1272527] = {
                    spellID = 1272527,
                    name = "爬行喷吐",
                    voiceCategory = 3,
                    sourceNPCIDs = { 253475, 255418 },
                    sources = { "Blistercreep" },
                },
            },
        },
        [3178] = {
            encounterID = 3178,
            dungeon = "虚影尖塔",
            boss = "威厄高尔和艾佐拉克 (Vaelgor & Ezzorak)",
            spells = {
                [1244672] = {
                    spellID = 1244672,
                    name = "虚界",
                    voiceCategory = 3,
                    sourceNPCIDs = { 242056 },
                    sources = { "Vaelgor" },
                },
                [1245175] = {
                    spellID = 1245175,
                    name = "虚空箭",
                    voiceCategory = 3,
                    sourceNPCIDs = { 248143 },
                    sources = { "Voidorb" },
                },
                [1245421] = {
                    spellID = 1245421,
                    name = "阴霾区域",
                    voiceCategory = 3,
                    sourceNPCIDs = { 244552 },
                    sources = { "Ezzorak" },
                },
                [1245554] = {
                    spellID = 1245554,
                    name = "阴霾触摸",
                    voiceCategory = 3,
                    sourceNPCIDs = { 244552 },
                    sources = { "Ezzorak" },
                },
                [1249595] = {
                    spellID = 1249595,
                    name = "辐光屏障",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    sources = { "War Chaplain Senn" },
                },
                [1252157] = {
                    spellID = 1252157,
                    name = "虚界",
                    voiceCategory = 3,
                    sourceNPCIDs = { 242056 },
                    sources = { "Vaelgor" },
                },
                [1255612] = {
                    spellID = 1255612,
                    name = "亡者吐息",
                    voiceCategory = 3,
                    sourceNPCIDs = { 242056, 254848 },
                    sources = { "Astral Reflection", "Vaelgor" },
                },
                [1255763] = {
                    spellID = 1255763,
                    name = "午夜化身",
                    voiceCategory = 3,
                    sourceNPCIDs = { 253342 },
                    sources = { "Xal'atath" },
                },
                [1262676] = {
                    spellID = 1262676,
                    name = "虚无光束",
                    voiceCategory = 3,
                    sourceNPCIDs = { 242056 },
                    sources = { "Vaelgor" },
                },
                [1264467] = {
                    spellID = 1264467,
                    name = "龙尾扫击",
                    voiceCategory = 3,
                    sourceNPCIDs = { 242056 },
                    sources = { "Vaelgor" },
                },
                [1265152] = {
                    spellID = 1265152,
                    name = "穿刺",
                    voiceCategory = 3,
                    sourceNPCIDs = { 244552 },
                    sources = { "Ezzorak" },
                },
                [1270497] = {
                    spellID = 1270497,
                    name = "暗影印记",
                    voiceCategory = 3,
                    sourceNPCIDs = { 249313 },
                    sources = { "Manifestation of Midnight" },
                },
                [1270852] = {
                    spellID = 1270852,
                    name = "削弱",
                    voiceCategory = 3,
                    sourceNPCIDs = { 244552 },
                    sources = { "Ezzorak" },
                },
                [1280355] = {
                    spellID = 1280355,
                    name = "拉克獠牙",
                    voiceCategory = 3,
                    sourceNPCIDs = { 244552 },
                    sources = { "Ezzorak" },
                },
            },
        },
        [3179] = {
            encounterID = 3179,
            dungeon = "虚影尖塔",
            boss = "陨落之王萨哈达尔 (Fallen-King Salhadaar)",
            spells = {
                [1245592] = {
                    spellID = 1245592,
                    name = "痛苦精粹",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240432 },
                    sources = { "Fallen-King Salhadaar" },
                },
                [1245960] = {
                    spellID = 1245960,
                    name = "虚空灌输",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240432 },
                    sources = { "Fallen-King Salhadaar" },
                },
                [1248697] = {
                    spellID = 1248697,
                    name = "专制命令",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240432 },
                    sources = { "Fallen-King Salhadaar" },
                },
                [1248709] = {
                    spellID = 1248709,
                    name = "压抑黑暗",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240432 },
                    sources = { "Fallen-King Salhadaar" },
                },
                [1250686] = {
                    spellID = 1250686,
                    name = "扭曲遮蔽",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240432 },
                    sources = { "Fallen-King Salhadaar" },
                },
                [1250828] = {
                    spellID = 1250828,
                    name = "虚空暴露",
                    voiceCategory = 3,
                    sourceNPCIDs = { 246665, 255078, 255280 },
                    sources = { "Concentrated Void", "Enduring Void" },
                },
                [1250991] = {
                    spellID = 1250991,
                    name = "晦暗侵蚀",
                    voiceCategory = 3,
                    sourceNPCIDs = { 246665 },
                    sources = { "Concentrated Void" },
                },
                [1251213] = {
                    spellID = 1251213,
                    name = "暮光尖峰",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240432 },
                    sources = { "Fallen-King Salhadaar" },
                },
                [1260030] = {
                    spellID = 1260030,
                    name = "本影迸流",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240432 },
                    sources = { "Fallen-King Salhadaar" },
                },
                [1271579] = {
                    spellID = 1271579,
                    name = "影蚀打击",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240432 },
                    sources = { "Fallen-King Salhadaar" },
                },
            },
        },
        [3180] = {
            encounterID = 3180,
            dungeon = "虚影尖塔",
            boss = "光盲先锋军 (Lightblinded Vanguard)",
            spells = {
                [1246158] = {
                    spellID = 1246158,
                    name = "奉献",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240431 },
                    sources = { "General Amias Bellamy" },
                },
                [1246487] = {
                    spellID = 1246487,
                    name = "复仇者之盾",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240431 },
                    sources = { "General Amias Bellamy" },
                },
                [1246502] = {
                    spellID = 1246502,
                    name = "复仇者之盾",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240431 },
                    sources = { "General Amias Bellamy" },
                },
                [1246736] = {
                    spellID = 1246736,
                    name = "审判",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240437 },
                    sources = { "Commander Venel Lightblood" },
                },
                [1248652] = {
                    spellID = 1248652,
                    name = "圣洁鸣钟",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240431 },
                    sources = { "General Amias Bellamy" },
                },
                [1248721] = {
                    spellID = 1248721,
                    name = "提尔之怒",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240438 },
                    sources = { "War Chaplain Senn" },
                },
                [1248994] = {
                    spellID = 1248994,
                    name = "处决宣判",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240437 },
                    sources = { "Commander Venel Lightblood" },
                },
                [1249024] = {
                    spellID = 1249024,
                    name = "处决宣判",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240437 },
                    sources = { "Commander Venel Lightblood" },
                },
                [1251857] = {
                    spellID = 1251857,
                    name = "审判",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240431 },
                    sources = { "General Amias Bellamy" },
                },
                [1258514] = {
                    spellID = 1258514,
                    name = "盲目之光",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240438 },
                    sources = { "War Chaplain Senn" },
                },
                [1272324] = {
                    spellID = 1272324,
                    name = "神恩风暴",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240437 },
                    sources = { "Commander Venel Lightblood" },
                },
                [1276982] = {
                    spellID = 1276982,
                    name = "神圣奉献",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240431, 240438 },
                    sources = { "General Amias Bellamy", "War Chaplain Senn" },
                },
            },
        },
        [3181] = {
            encounterID = 3181,
            dungeon = "虚影尖塔",
            boss = "宇宙之冕 (Crown of the Cosmos)",
            spells = {
                [1227557] = {
                    spellID = 1227557,
                    name = "噬灭宇宙",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    sources = { "Environment" },
                },
                [1232470] = {
                    spellID = 1232470,
                    name = "空虚之握",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240430 },
                    sources = { "Alleria Windrunner" },
                },
                [1233602] = {
                    spellID = 1233602,
                    name = "银锋箭",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240430 },
                    sources = { "Alleria Windrunner" },
                },
                [1233865] = {
                    spellID = 1233865,
                    name = "空无之冕",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240430, 245113 },
                    sources = { "Alleria Windrunner", "Rift Simulacrum" },
                },
                [1233887] = {
                    spellID = 1233887,
                    name = "空无之冕",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    sources = { "Environment" },
                },
                [1234570] = {
                    spellID = 1234570,
                    name = "星辰散射",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240430 },
                    sources = { "Alleria Windrunner" },
                },
                [1237038] = {
                    spellID = 1237038,
                    name = "虚空追猎者钉刺",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240430 },
                    sources = { "Alleria Windrunner" },
                },
                [1238206] = {
                    spellID = 1238206,
                    name = "无常裂隙",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    sources = { "Environment" },
                },
                [1238708] = {
                    spellID = 1238708,
                    name = "黑暗冲锋",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    sources = { "Environment" },
                },
                [1239111] = {
                    spellID = 1239111,
                    name = "终末守护",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240430 },
                    sources = { "Alleria Windrunner" },
                },
                [1242553] = {
                    spellID = 1242553,
                    name = "虚空残渣",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240430 },
                    sources = { "Alleria Windrunner" },
                },
                [1243753] = {
                    spellID = 1243753,
                    name = "暴食深渊",
                    voiceCategory = 3,
                    sourceNPCIDs = { 243811 },
                    sources = { "Vorelus" },
                },
                [1243981] = {
                    spellID = 1243981,
                    name = "银锋弹幕射击",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240430 },
                    sources = { "Alleria Windrunner" },
                },
                [1246462] = {
                    spellID = 1246462,
                    name = "裂隙挥砍",
                    voiceCategory = 3,
                    sourceNPCIDs = { 245113 },
                    sources = { "Rift Simulacrum" },
                },
                [1255453] = {
                    spellID = 1255453,
                    name = "重力坍缩",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    sources = { "Environment" },
                },
                [1260027] = {
                    spellID = 1260027,
                    name = "空虚之握",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240430 },
                    sources = { "Alleria Windrunner" },
                },
                [1283236] = {
                    spellID = 1283236,
                    name = "虚空斥力",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240430 },
                    sources = { "Alleria Windrunner" },
                },
            },
        },
        [3182] = {
            encounterID = 3182,
            dungeon = "进军奎尔丹纳斯",
            boss = "贝洛朗，奥的子嗣 (Belo'ren, Child of Al'ar)",
            spells = {
                [1241292] = {
                    spellID = 1241292,
                    name = "圣光俯冲",
                    voiceCategory = 3,
                    sourceNPCIDs = { 246729 },
                    sources = { "Light Ember" },
                },
                [1241339] = {
                    spellID = 1241339,
                    name = "虚空俯冲",
                    voiceCategory = 3,
                    sourceNPCIDs = { 246728 },
                    sources = { "Void Ember" },
                },
                [1241840] = {
                    spellID = 1241840,
                    name = "圣光区域",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240387 },
                    sources = { "Belo'ren" },
                },
                [1241841] = {
                    spellID = 1241841,
                    name = "虚空区域",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240387 },
                    sources = { "Belo'ren" },
                },
                [1241992] = {
                    spellID = 1241992,
                    name = "圣光飞羽",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    sources = { "Environment" },
                },
                [1242091] = {
                    spellID = 1242091,
                    name = "虚空飞羽",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    sources = { "Environment" },
                },
                [1242803] = {
                    spellID = 1242803,
                    name = "圣光烈焰",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240387 },
                    sources = { "Belo'ren" },
                },
                [1242815] = {
                    spellID = 1242815,
                    name = "虚空烈焰",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240387 },
                    sources = { "Belo'ren" },
                },
                [1244348] = {
                    spellID = 1244348,
                    name = "圣光灼烧",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240387 },
                    sources = { "Belo'ren" },
                },
                [1266404] = {
                    spellID = 1266404,
                    name = "虚空灼烧",
                    voiceCategory = 3,
                    sourceNPCIDs = { 240387 },
                    sources = { "Belo'ren" },
                },
            },
        },
        [3183] = {
            encounterID = 3183,
            dungeon = "进军奎尔丹纳斯",
            boss = "至暗之夜降临 (Midnight Falls)",
            spells = {
                [1251789] = {
                    spellID = 1251789,
                    name = "宇宙裂隙",
                    voiceCategory = 3,
                    sourceNPCIDs = { 250615 },
                    sources = { "Midnight Crystal" },
                },
                [1253770] = {
                    spellID = 1253770,
                    name = "黎明光障",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    sources = { "Environment" },
                },
                [1276487] = {
                    spellID = 1276487,
                    name = "至终之光",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    sources = { "Environment" },
                },
                [1284527] = {
                    spellID = 1284527,
                    name = "充电",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    sources = { "Environment" },
                },
            },
        },
        [3212] = {
            encounterID = 3212,
            dungeon = "迈萨拉洞窟",
            boss = "姆罗金和内克拉克斯 (Muro'jin and Nekraxx)",
            spells = {
                [1249478] = {
                    spellID = 1249478,
                    name = "腐肉飞扑",
                    voiceCategory = 3,
                    sourceNPCIDs = { 247572 },
                    sources = { "Nekraxx" },
                },
                [1260643] = {
                    spellID = 1260643,
                    name = "弹幕射击",
                    voiceCategory = 3,
                    sourceNPCIDs = { 247570 },
                    sources = { "Muro'jin" },
                },
            },
        },
        [3213] = {
            encounterID = 3213,
            dungeon = "迈萨拉洞窟",
            boss = "沃达扎 (Vordaza)",
            spells = {
                [1251775] = {
                    spellID = 1251775,
                    name = "终极追杀",
                    voiceCategory = 3,
                    sourceNPCIDs = { 250443 },
                    sources = { "Unstable Phantom" },
                },
            },
        },
        [3214] = {
            encounterID = 3214,
            dungeon = "迈萨拉洞窟",
            boss = "拉克图尔，聚魂之器 (Rak'tul, Vessel of Souls)",
            spells = {
                [1252675] = {
                    spellID = 1252675,
                    name = "粉碎灵魂",
                    voiceCategory = 3,
                    sourceNPCIDs = { 248605 },
                    sources = { "Rak'tul" },
                },
            },
        },
        [3306] = {
            encounterID = 3306,
            dungeon = "梦境裂隙",
            boss = "奇美鲁斯，未梦之神 (Chimaerus the Undreamt God)",
            spells = {
                [1245698] = {
                    spellID = 1245698,
                    name = "艾林洞察",
                    voiceCategory = 3,
                    sourceNPCIDs = { 245569 },
                    sources = { "Chimaerus" },
                },
                [1246653] = {
                    spellID = 1246653,
                    name = "腐蚀黏痰",
                    voiceCategory = 3,
                    sourceNPCIDs = { 245569 },
                    sources = { "Chimaerus" },
                },
                [1253744] = {
                    spellID = 1253744,
                    name = "裂隙易伤",
                    voiceCategory = 3,
                    sourceNPCIDs = { 245569 },
                    sources = { "Chimaerus" },
                },
                [1257087] = {
                    spellID = 1257087,
                    name = "吞噬瘴气",
                    voiceCategory = 3,
                    sourceNPCIDs = { 245569 },
                    sources = { "Chimaerus" },
                },
                [1258192] = {
                    spellID = 1258192,
                    name = "残留瘴气",
                    voiceCategory = 3,
                    sourceNPCIDs = { 245569 },
                    sources = { "Chimaerus" },
                },
                [1264756] = {
                    spellID = 1264756,
                    name = "裂隙疯狂",
                    voiceCategory = 3,
                    sourceNPCIDs = { 245569 },
                    sources = { "Chimaerus" },
                },
                [1264757] = {
                    spellID = 1264757,
                    name = "裂隙疯狂",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    sources = { "Environment" },
                },
                [1265940] = {
                    spellID = 1265940,
                    name = "可怖战吼",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    sources = { "Environment" },
                },
                [1272726] = {
                    spellID = 1272726,
                    name = "猛撕开裂",
                    voiceCategory = 3,
                    sourceNPCIDs = { 245569 },
                    sources = { "Chimaerus" },
                },
            },
        },
        [3328] = {
            encounterID = 3328,
            dungeon = "节点希纳斯",
            boss = "核技工程长卡斯雷瑟 (Chief Corewright Kasreth)",
            spells = {
                [1251772] = {
                    spellID = 1251772,
                    name = "回流充能",
                    voiceCategory = 3,
                    sourceNPCIDs = { 241539 },
                    sources = { "Kasreth" },
                },
                [1257836] = {
                    spellID = 1257836,
                    name = "回流充能",
                    voiceCategory = 3,
                    sourceNPCIDs = { 241539 },
                    sources = { "Kasreth" },
                },
            },
        },
        [3332] = {
            encounterID = 3332,
            dungeon = "节点希纳斯",
            boss = "核心守卫奈萨拉 (Corewarden Nysarra)",
            spells = {
                [1249020] = {
                    spellID = 1249020,
                    name = "蚀光步伐",
                    voiceCategory = 3,
                    sourceNPCIDs = { 241542 },
                    sources = { "Corewarden Nysarra" },
                },
                [1252828] = {
                    spellID = 1252828,
                    name = "虚空创裂",
                    voiceCategory = 3,
                    sourceNPCIDs = { 241542 },
                    sources = { "Corewarden Nysarra" },
                },
                [1282678] = {
                    spellID = 1282678,
                    name = "钉锤风暴",
                    voiceCategory = 3,
                    sourceNPCIDs = { 251024 },
                    sources = { "Dreadflail" },
                },
            },
        },
    },
    mplus = {
        ["执政团之座"] = {
            dungeon = "执政团之座",
            dungeonEN = "Seat of the Triumvirate",
            spells = {
                [244588] = {
                    spellID = 244588,
                    name = "虚空淤泥",
                    voiceCategory = 2,
                    sourceNPCIDs = {},
                    bosses = { "晋升者祖拉尔" },
                    sources = { "Environment" },
                },
                [244599] = {
                    spellID = 244599,
                    name = "黑暗驱逐",
                    voiceCategory = 3,
                    sourceNPCIDs = { 122716 },
                    bosses = { "晋升者祖拉尔" },
                    sources = { "Coalesced Void" },
                },
                [246026] = {
                    spellID = 246026,
                    name = "虚空炸弹",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    bosses = { "萨普瑞什" },
                    sources = { "Environment" },
                },
                [248831] = {
                    spellID = 248831,
                    name = "恐惧尖啸",
                    voiceCategory = 3,
                    sourceNPCIDs = { 125340 },
                    bosses = {},
                    sources = { "Shadewing" },
                },
                [1263523] = {
                    spellID = 1263523,
                    name = "过载",
                    voiceCategory = 3,
                    sourceNPCIDs = { 122316 },
                    bosses = { "萨普瑞什" },
                    sources = { "Saprish" },
                },
                [1263532] = {
                    spellID = 1263532,
                    name = "虚空风暴",
                    voiceCategory = 3,
                    sourceNPCIDs = { 122056 },
                    bosses = { "总督奈扎尔" },
                    sources = { "Viceroy Nezhar" },
                },
                [1263542] = {
                    spellID = 1263542,
                    name = "群体虚空灌输",
                    voiceCategory = 3,
                    sourceNPCIDs = { 122056 },
                    bosses = { "总督奈扎尔" },
                    sources = { "Viceroy Nezhar" },
                },
                [1265426] = {
                    spellID = 1265426,
                    name = "不谐射线",
                    voiceCategory = 1,
                    sourceNPCIDs = { 124729 },
                    bosses = { "鲁拉" },
                    sources = { "L'ura" },
                },
                [1265650] = {
                    spellID = 1265650,
                    name = "苦痛",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    bosses = { "鲁拉" },
                    sources = { "Environment" },
                },
                [1268733] = {
                    spellID = 1268733,
                    name = "精神鞭笞",
                    voiceCategory = 3,
                    sourceNPCIDs = { 122827 },
                    bosses = { "总督奈扎尔" },
                    sources = { "Umbral Tentacle" },
                },
                [1268840] = {
                    spellID = 1268840,
                    name = "渗透虚空",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    bosses = { "萨普瑞什" },
                    sources = { "Void Bomb" },
                },
            },
        },
        ["艾杰斯亚学院"] = {
            dungeon = "艾杰斯亚学院",
            dungeonEN = "Algeth'ar Academy",
            spells = {
                [376760] = {
                    spellID = 376760,
                    name = "狂风之力",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    bosses = {},
                    sources = { "Goal of the Rushing Winds" },
                },
                [377009] = {
                    spellID = 377009,
                    name = "震耳尖啸",
                    voiceCategory = 3,
                    sourceNPCIDs = { 191736 },
                    bosses = { "克罗兹" },
                    sources = { "Crawth" },
                },
                [386201] = {
                    spellID = 386201,
                    name = "腐化法力",
                    voiceCategory = 2,
                    sourceNPCIDs = { 194181 },
                    bosses = { "维克萨姆斯" },
                    sources = { "Vexamus" },
                },
                [388544] = {
                    spellID = 388544,
                    name = "裂树击",
                    voiceCategory = 3,
                    sourceNPCIDs = { 196482 },
                    bosses = { "茂林古树" },
                    sources = { "Overgrown Ancient" },
                },
                [389011] = {
                    spellID = 389011,
                    name = "势不可挡",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    bosses = {},
                    sources = { "Environment" },
                },
                [391977] = {
                    spellID = 391977,
                    name = "涌动超载",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    bosses = {},
                    sources = { "Environment" },
                },
            },
        },
        ["节点希纳斯"] = {
            dungeon = "节点希纳斯",
            dungeonEN = "Nexus-Point Xenas",
            spells = {
                [1249020] = {
                    spellID = 1249020,
                    name = "蚀光步伐",
                    voiceCategory = 1,
                    sourceNPCIDs = { 241542 },
                    bosses = { "核心守卫奈萨拉" },
                    sources = { "Corewarden Nysarra" },
                },
                [1251772] = {
                    spellID = 1251772,
                    name = "回流充能",
                    voiceCategory = 3,
                    sourceNPCIDs = { 241539 },
                    bosses = {},
                    sources = { "Kasreth" },
                },
                [1252828] = {
                    spellID = 1252828,
                    name = "虚空创裂",
                    voiceCategory = 3,
                    sourceNPCIDs = { 241542 },
                    bosses = { "核心守卫奈萨拉" },
                    sources = { "Corewarden Nysarra" },
                },
                [1257836] = {
                    spellID = 1257836,
                    name = "回流充能",
                    voiceCategory = 3,
                    sourceNPCIDs = { 241539 },
                    bosses = {},
                    sources = { "Kasreth" },
                },
            },
        },
        ["萨隆矿坑"] = {
            dungeon = "萨隆矿坑",
            dungeonEN = "Pit of Saron",
            spells = {
                [1261286] = {
                    spellID = 1261286,
                    name = "投掷萨隆邪铁",
                    voiceCategory = 2,
                    sourceNPCIDs = { 252635 },
                    bosses = { "熔炉之主加弗斯特" },
                    sources = { "Forgemaster Garfrost" },
                },
                [1261540] = {
                    spellID = 1261540,
                    name = "碎矿猛击",
                    voiceCategory = 3,
                    sourceNPCIDs = { 252635 },
                    bosses = { "熔炉之主加弗斯特" },
                    sources = { "Forgemaster Garfrost" },
                },
                [1261799] = {
                    spellID = 1261799,
                    name = "萨隆邪铁淤泥",
                    voiceCategory = 2,
                    sourceNPCIDs = { 252635 },
                    bosses = { "熔炉之主加弗斯特" },
                    sources = { "Forgemaster Garfrost" },
                },
                [1261966] = {
                    spellID = 1261966,
                    name = "碎矿猛击",
                    voiceCategory = 3,
                    sourceNPCIDs = { 252635 },
                    bosses = { "熔炉之主加弗斯特" },
                    sources = { "Forgemaster Garfrost" },
                },
                [1262596] = {
                    spellID = 1262596,
                    name = "天灾领主的印记",
                    voiceCategory = 3,
                    sourceNPCIDs = { 252648 },
                    bosses = { "天灾领主泰兰努斯" },
                    sources = { "Scourgelord Tyrannus" },
                },
                [1262772] = {
                    spellID = 1262772,
                    name = "白霜冲击",
                    voiceCategory = 1,
                    sourceNPCIDs = { 252653 },
                    bosses = { "天灾领主泰兰努斯" },
                    sources = { "Rimefang" },
                },
                [1263716] = {
                    spellID = 1263716,
                    name = "冰霜撕咬",
                    voiceCategory = 3,
                    sourceNPCIDs = { 252653 },
                    bosses = { "天灾领主泰兰努斯" },
                    sources = { "Rimefang" },
                },
                [1263766] = {
                    spellID = 1263766,
                    name = "死亡之握",
                    voiceCategory = 2,
                    sourceNPCIDs = { 252648 },
                    bosses = { "天灾领主泰兰努斯" },
                    sources = { "Scourgelord Tyrannus" },
                },
                [1264246] = {
                    spellID = 1264246,
                    name = "暗影转移",
                    voiceCategory = 3,
                    sourceNPCIDs = { 252621 },
                    bosses = { "伊克和科瑞克" },
                    sources = { "Krick" },
                },
                [1264299] = {
                    spellID = 1264299,
                    name = "凋零",
                    voiceCategory = 2,
                    sourceNPCIDs = { 252625 },
                    bosses = { "伊克和科瑞克" },
                    sources = { "Ick" },
                },
                [1264453] = {
                    spellID = 1264453,
                    name = "笨重凝视",
                    voiceCategory = 1,
                    sourceNPCIDs = { 252625 },
                    bosses = { "伊克和科瑞克" },
                    sources = { "Ick" },
                },
                [1264595] = {
                    spellID = 1264595,
                    name = "暗影射线屏障",
                    voiceCategory = 2,
                    sourceNPCIDs = {},
                    bosses = { "伊克和科瑞克" },
                    sources = { "Environment" },
                },
                [1271679] = {
                    spellID = 1271679,
                    name = "暗影炸弹",
                    voiceCategory = 3,
                    sourceNPCIDs = { 255037 },
                    bosses = { "伊克和科瑞克" },
                    sources = { "Shade of Krick" },
                },
                [1275687] = {
                    spellID = 1275687,
                    name = "冰川过载",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    bosses = { "熔炉之主加弗斯特" },
                    sources = { "Forge" },
                },
                [1276648] = {
                    spellID = 1276648,
                    name = "骸骨灌注",
                    voiceCategory = 3,
                    sourceNPCIDs = { 252648 },
                    bosses = { "天灾领主泰兰努斯" },
                    sources = { "Scourgelord Tyrannus" },
                },
                [1279708] = {
                    spellID = 1279708,
                    name = "室内凋零",
                    voiceCategory = 3,
                    sourceNPCIDs = {},
                    bosses = {},
                    sources = { "Environment" },
                },
            },
        },
        ["迈萨拉洞窟"] = {
            dungeon = "迈萨拉洞窟",
            dungeonEN = "Maisara Caverns",
            spells = {
                [1249478] = {
                    spellID = 1249478,
                    name = "腐肉飞扑",
                    voiceCategory = 1,
                    sourceNPCIDs = { 247572 },
                    bosses = {},
                    sources = { "Nekraxx" },
                },
                [1251775] = {
                    spellID = 1251775,
                    name = "终极追杀",
                    voiceCategory = 3,
                    sourceNPCIDs = { 250443 },
                    bosses = {},
                    sources = { "Unstable Phantom" },
                },
                [1252675] = {
                    spellID = 1252675,
                    name = "粉碎灵魂",
                    voiceCategory = 2,
                    sourceNPCIDs = { 248605 },
                    bosses = {},
                    sources = { "Rak'tul" },
                },
                [1260643] = {
                    spellID = 1260643,
                    name = "弹幕射击",
                    voiceCategory = 1,
                    sourceNPCIDs = { 247570 },
                    bosses = {},
                    sources = { "Muro'jin" },
                },
            },
        },
        ["通天峰"] = {
            dungeon = "通天峰",
            dungeonEN = "Skyreach",
            spells = {
                [154132] = {
                    spellID = 154132,
                    name = "灼热重击",
                    voiceCategory = 2,
                    sourceNPCIDs = { 76141 },
                    bosses = { "阿拉卡纳斯" },
                    sources = { "Araknath" },
                },
                [154150] = {
                    spellID = 154150,
                    name = "光线",
                    voiceCategory = 3,
                    sourceNPCIDs = { 76142 },
                    bosses = { "阿拉卡纳斯" },
                    sources = { "Skyreach Sun Construct Prototype" },
                },
                [1252733] = {
                    spellID = 1252733,
                    name = "疾风奔涌",
                    voiceCategory = 3,
                    sourceNPCIDs = { 75964 },
                    bosses = { "兰吉特" },
                    sources = { "Ranjit" },
                },
                [1253511] = {
                    spellID = 1253511,
                    name = "爆燃追击",
                    voiceCategory = 1,
                    sourceNPCIDs = { 76227 },
                    bosses = { "鲁克兰" },
                    sources = { "Sunwing" },
                },
                [1253520] = {
                    spellID = 1253520,
                    name = "燃烧之爪",
                    voiceCategory = 3,
                    sourceNPCIDs = { 76143 },
                    bosses = { "鲁克兰" },
                    sources = { "Rukhran" },
                },
                [1253541] = {
                    spellID = 1253541,
                    name = "灼烧射线",
                    voiceCategory = 3,
                    sourceNPCIDs = { 76266 },
                    bosses = { "高阶贤者维里克斯" },
                    sources = { "High Sage Viryx" },
                },
                [1279002] = {
                    spellID = 1279002,
                    name = "冲击波",
                    voiceCategory = 2,
                    sourceNPCIDs = { 76141 },
                    bosses = { "阿拉卡纳斯" },
                    sources = { "Araknath" },
                },
            },
        },
        ["风行者之塔"] = {
            dungeon = "风行者之塔",
            dungeonEN = "Windrunner Spire",
            spells = {
                [467620] = {
                    spellID = 467620,
                    name = "暴怒",
                    voiceCategory = 3,
                    sourceNPCIDs = { 231631 },
                    bosses = { "指挥官克罗鲁科" },
                    sources = { "Commander Kroluk" },
                },
                [470966] = {
                    spellID = 470966,
                    name = "剑刃风暴",
                    voiceCategory = 2,
                    sourceNPCIDs = {},
                    bosses = {},
                    sources = { "Environment" },
                },
                [472662] = {
                    spellID = 472662,
                    name = "暴风斩",
                    voiceCategory = 3,
                    sourceNPCIDs = { 231636 },
                    bosses = { "无眠之心" },
                    sources = { "Restless Heart" },
                },
                [472793] = {
                    spellID = 472793,
                    name = "猛力拖拽",
                    voiceCategory = 1,
                    sourceNPCIDs = { 231629 },
                    bosses = {},
                    sources = { "Latch" },
                },
                [474129] = {
                    spellID = 474129,
                    name = "飞溅喷吐",
                    voiceCategory = 3,
                    sourceNPCIDs = { 231629 },
                    bosses = {},
                    sources = { "Latch" },
                },
                [1253979] = {
                    spellID = 1253979,
                    name = "劲风射击",
                    voiceCategory = 2,
                    sourceNPCIDs = { 231636 },
                    bosses = { "无眠之心" },
                    sources = { "Restless Heart" },
                },
                [1282911] = {
                    spellID = 1282911,
                    name = "飞矢烈风",
                    voiceCategory = 1,
                    sourceNPCIDs = { 231636 },
                    bosses = { "无眠之心" },
                    sources = { "Restless Heart" },
                },
                [1283247] = {
                    spellID = 1283247,
                    name = "无情跳跃",
                    voiceCategory = 1,
                    sourceNPCIDs = { 231631 },
                    bosses = { "指挥官克罗鲁科" },
                    sources = { "Commander Kroluk" },
                },
            },
        },
        ["魔导师平台"] = {
            dungeon = "魔导师平台",
            dungeonEN = "Magisters' Terrace",
            spells = {
                [1225792] = {
                    spellID = 1225792,
                    name = "符文印记",
                    voiceCategory = 1,
                    sourceNPCIDs = { 231863 },
                    bosses = {},
                    sources = { "Seranel Sunlash" },
                },
                [1253709] = {
                    spellID = 1253709,
                    name = "神经链接",
                    voiceCategory = 1,
                    sourceNPCIDs = { 231864, 239636 },
                    bosses = { "吉美尔鲁斯" },
                    sources = { "Gemellus" },
                },
                [1269631] = {
                    spellID = 1269631,
                    name = "熵能宝珠",
                    voiceCategory = 2,
                    sourceNPCIDs = { 231865 },
                    bosses = { "迪詹崔乌斯" },
                    sources = { "Degentrius" },
                },
            },
        },
    },
}
