_G.EXBossData.RegisterBossPreset("mplus_dps", {
    key = "B",
    name = "[CN] 绿色歹人 - DPS",
    author = "B作者",
    builtIn = true,
    events = {
        [16] = {
            enabled = false,
        },
        [21] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            preAlertText = "准备踩箭",
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "准备踩箭",
        },
        [24] = {
            enabled = false,
        },
        [25] = {
            enabled = false,
        },
        [27] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            preAlertText = "准备AOE",
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = true,
                    ringEnabled = true,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "准备AOE",
        },
        [28] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            preAlertText = "点名放水",
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "点名放水",
        },
        [35] = {
            enabled = false,
        },
        [94] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            enabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "坦克尖刺",
        },
        [95] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "准备消层",
        },
        [107] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            preAlertText = "点名消线",
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "点名消线",
        },
        [111] = {
            enabled = false,
        },
        [144] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            enabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "坦克尖刺",
        },
        [145] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "准备AOE",
        },
        [146] = {
            centralLead = 0,
            countdownEnabled = false,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            enabled = false,
            preAlert = 0,
            preAlertEnabled = false,
            preAlertText = "注意躲避",
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "注意躲避",
        },
        [147] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "快卡视角",
        },
        [150] = {
            centralLead = 0,
            centralText = "",
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            enabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            preAlertText = "坦克尖刺",
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "坦克尖刺",
        },
        [152] = {
            centralLead = 0,
            preAlert = 5,
            preAlertEnabled = true,
            preAlertText = "注意躲避",
            rules = {
                castWindow = {
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "注意躲避",
            triggers = {
                [1] = {
                    fixedOffsetMode = "delay",
                    fixedOffsetSeconds = 0,
                },
                [2] = {
                    fixedOffsetMode = "delay",
                    fixedOffsetSeconds = 0,
                },
            },
        },
        [156] = {
            enabled = false,
        },
        [164] = {
            enabled = false,
        },
        [167] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "准备AOE",
        },
        [204] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "准备AOE",
        },
        [206] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            enabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "坦克尖刺",
        },
        [210] = {
            enabled = false,
        },
        [226] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            enabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            preAlertText = "坦克尖刺",
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    interruptCheckEnabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "坦克尖刺",
        },
        [236] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            preAlertText = "快打断",
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    interruptCheckEnabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "快打断",
        },
        [239] = {
            enabled = false,
        },
        [241] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            preAlertText = "准备点名",
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = true,
                    interruptCheckEnabled = false,
                    ringEnabled = true,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "准备点名",
        },
        [244] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "准备打断",
        },
        [248] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "准备AOE",
        },
        [251] = {
            centralLead = 0,
            color = {
                enabled = false,
            },
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            enabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "准备跑圈",
            triggers = {
                [0] = {
                    sourceType = "pack",
                },
                [1] = {
                    sourceType = "pack",
                },
                [2] = {
                    sourceType = "pack",
                },
            },
        },
        [274] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "注意挡球",
        },
        [276] = {
            enabled = false,
        },
        [278] = {
            enabled = false,
            rules = {
                castWindow = {
                    enabled = true,
                    interruptCheckEnabled = true,
                    ringEnabled = true,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
        },
        [282] = {
            enabled = false,
        },
        [286] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            enabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "坦克尖刺",
        },
        [294] = {
            enabled = false,
        },
        [298] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "注意击退",
        },
        [302] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            enabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "坦克尖刺",
        },
        [306] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            enabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "坦克尖刺",
        },
        [309] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "准备点名",
        },
        [420] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            enabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "坦克尖刺",
        },
        [556] = {
            enabled = false,
        },
        [635] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
        },
        [100001] = {
            centralLead = 0,
            countdownEnabled = true,
            countdownLead = 5,
            countdownPlayName = false,
            countdownVoiceEnabled = false,
            enabled = false,
            preAlert = 5,
            preAlertEnabled = true,
            rules = {
                castWindow = {
                    castBarEnabled = false,
                    castBarRenameEnabled = false,
                    castBarRenameText = "",
                    castCheckEnabled = false,
                    enabled = false,
                    ringEnabled = false,
                    windowAfter = 2,
                    windowBefore = 1,
                },
            },
            timerBarRenameEnabled = false,
            timerBarRenameText = "坦克尖刺",
        },
    },
    privateAura = {
        categories = {},
        entries = {
            ["pa:mplus:boss:萨隆矿坑:熔炉之主加弗斯特:1261286"] = {
                customLSM = "",
                customPath = "",
                enabled = true,
                label = "",
                sourceType = "pack",
            },
            ["pa:mplus:boss:萨隆矿坑:熔炉之主加弗斯特:1261540"] = {
                customLSM = "",
                customPath = "",
                enabled = true,
                label = "",
                sourceType = "pack",
            },
            ["pa:mplus:boss:萨隆矿坑:熔炉之主加弗斯特:1261799"] = {
                customLSM = "",
                customPath = "",
                enabled = true,
                label = "",
                sourceType = "pack",
            },
            ["pa:mplus:boss:萨隆矿坑:熔炉之主加弗斯特:1275687"] = {
                customLSM = "",
                customPath = "",
                enabled = true,
                label = "",
                sourceType = "pack",
            },
        },
    },
})
